function [fitresult, gof] = createFit_pond_All(A)
%CREATEFIT(A)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      Y Output: A
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 27-Mar-2018 18:25:38


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( [], A );

% Set up fittype and options.
ft = fittype( 'poly1' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% Plot fit with data.
%figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'A', 'Fitt, f(x)=ax+b', 'Location', 'NorthEast' );
% Label axes
ylabel A
grid on


