function createfigure(YMatrix1)
%CREATEFIGURE(YMATRIX1)
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 27-Mar-2018 19:33:18

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,...
    'XTickLabel',{'','SA','','SP','','NP','','CP',''},...
    'FontWeight','bold',...
    'FontSize',30);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0.5 4.5]);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(YMatrix1,'MarkerSize',10,'Marker','o','LineStyle','none',...
    'Parent',axes1);
set(plot1(1),'DisplayName','Lambert',...
    'MarkerFaceColor',[0 0.447058826684952 0.74117648601532]);
set(plot1(2),'DisplayName','Albani','MarkerFaceColor',[1 0 0],...
    'Color',[1 0 0]);
set(plot1(3),'DisplayName','MRI-CGCM3',...
    'MarkerFaceColor',[0.929411768913269 0.694117665290833 0.125490203499794]);

% Create xlabel
xlabel('Regiones HNLC','FontSize',40);

% Create ylabel
ylabel('% de Reducción ','FontSize',40);

% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.746525899546605 0.708776598003633 0.144017322004067 0.160460988389896],...
    'FontSize',24);

