function [fitresult, gof] = createFit1(Dust, dCO2)
%CREATEFIT1(DUST,DCO2)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : Dust
%      Y Output: dCO2
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 26-Mar-2018 16:32:59


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( Dust, dCO2 );

% Set up fittype and options.
ft = fittype( 'poly1' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );
set(gcf,'position',[200 300 800 500])
set(gcf,'PaperPosition',[0 0 1150/100 500/100]);
% Create a figure for the plots.
%figure( 'Name', 'untitled fit 1' );

% Plot fit with data.
%subplot( 2, 1, 1 );
plot( fitresult, xData, yData,'o' );
box off
axis([Dust(1) Dust(10) dCO2(1) dCO2(10)])

legend('pCO_2 vs. Dust Flux', 'Fit, f(x) = ax+b', 'Location', 'southeast' );
% legend('pCO_2 vs. Flujo de Polvo', 'Ajuste, f(x) = ax+b', 'Location', 'southeast' );

% Label axes
xlabel('\bf{Dust Flux ($\frac{kg}{s}$)}','FontSize',24,...
    'Interpreter','latex')
ylabel('pCO_2 (ppm) Reduction ','FontWeight','bold','FontSize',24);
% xlabel('\bf{Flujo de polvo ($\frac{kg}{s}$)}','FontSize',24,...
%     'Interpreter','latex')
% ylabel('Reducción pCO_2 (ppm) ','FontWeight','bold','FontSize',24);
grid on

% Plot residuals.
% subplot( 2, 1, 2 );
% h = plot( fitresult, xData, yData, 'residuals' );
% legend( h, 'untitled fit 1 - residuals', 'Zero Line', 'Location', 'NorthEast' );
% % Label axes
% xlabel Dust
% ylabel dCO2
% grid on


