function [fitresult, gof] = createFit(Dust, dCO2)
%CREATEFIT(DUST,DCO2)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : Dust
%      Y Output: dCO2
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 22-Mar-2018 17:37:32


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( Dust, dCO2 );

% Set up fittype and options.
ft = fittype( 'a+b/x+c*log(x)', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.566132665052171 0.0311807958891205 0.580175038825271];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Create a figure for the plots.
%set(gcf,'position',[200 300 800 500])
%set(gcf,'PaperPosition',[0 0 2900/100 1270/100]);

set(gcf,'position',[200 300 800 500])
set(gcf,'PaperPosition',[0 0 1150/100 500/100]);

% Plot fit with data.
%subplot( 2, 1, 1 );
plot(fitresult, xData, yData,'o');
set(gca,'FontSize',14)
box off
 legend('pCO_2 vs. Dust Flux', 'Fit, f(x) = a+b/x+c*log(x)', 'Location', 'southeast');
% legend( 'pCO_2 vs. Flujo de polvo', 'Ajuste, f(x) = a+b/x+c*log(x)', 'Location', 'southeast' );
% Label axes

xlabel('\bf{Dust Flux ($\frac{kg}{s}$)}','FontSize',26,...
    'Interpreter','latex')
ylabel('pCO_2 (ppm) Reduction ','FontWeight','bold','FontSize',26);
% xlabel('\bf{Flujo de polvo ($\frac{kg}{s}$)}','FontSize',24,...
%     'Interpreter','latex')
% ylabel('Reducción pCO_2 (ppm) ','FontWeight','bold','FontSize',24);
grid on

% Plot residuals.
% subplot( 2, 1, 2 );
% plot( fitresult, xData, yData, 'residuals' );
% % Label axes
% xlabel Dust
% ylabel dCO2
% grid on


